// <auto-generated />
using System;
using FlightCheckin.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightCheckin.DataAccess.Migrations
{
    [DbContext(typeof(FlightContext))]
    partial class FlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FlightCheckin.Models.BoardingPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BoardingPasses");
                });

            modelBuilder.Entity("FlightCheckin.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new DateTime(2025, 8, 22, 11, 28, 18, 899, DateTimeKind.Utc).AddTicks(96),
                            Destination = "Tokyo (NRT)",
                            FlightNumber = "MGL101",
                            Status = 0
                        });
                });

            modelBuilder.Entity("FlightCheckin.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlightCheckin.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedPassengerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Column")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedPassengerId");

                    b.HasIndex("FlightId", "Row", "Column")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 1
                        },
                        new
                        {
                            Id = 2,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 1
                        },
                        new
                        {
                            Id = 3,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 1
                        },
                        new
                        {
                            Id = 4,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 1
                        },
                        new
                        {
                            Id = 5,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 1
                        },
                        new
                        {
                            Id = 6,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 1
                        },
                        new
                        {
                            Id = 7,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 2
                        },
                        new
                        {
                            Id = 8,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 2
                        },
                        new
                        {
                            Id = 9,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 2
                        },
                        new
                        {
                            Id = 10,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 2
                        },
                        new
                        {
                            Id = 11,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 2
                        },
                        new
                        {
                            Id = 12,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 2
                        },
                        new
                        {
                            Id = 13,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 3
                        },
                        new
                        {
                            Id = 14,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 3
                        },
                        new
                        {
                            Id = 15,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 3
                        },
                        new
                        {
                            Id = 16,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 3
                        },
                        new
                        {
                            Id = 17,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 3
                        },
                        new
                        {
                            Id = 18,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 3
                        },
                        new
                        {
                            Id = 19,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 4
                        },
                        new
                        {
                            Id = 20,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 4
                        },
                        new
                        {
                            Id = 21,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 4
                        },
                        new
                        {
                            Id = 22,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 4
                        },
                        new
                        {
                            Id = 23,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 4
                        },
                        new
                        {
                            Id = 24,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 4
                        },
                        new
                        {
                            Id = 25,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 5
                        },
                        new
                        {
                            Id = 26,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 5
                        },
                        new
                        {
                            Id = 27,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 5
                        },
                        new
                        {
                            Id = 28,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 5
                        },
                        new
                        {
                            Id = 29,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 5
                        },
                        new
                        {
                            Id = 30,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 5
                        },
                        new
                        {
                            Id = 31,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 6
                        },
                        new
                        {
                            Id = 32,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 6
                        },
                        new
                        {
                            Id = 33,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 6
                        },
                        new
                        {
                            Id = 34,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 6
                        },
                        new
                        {
                            Id = 35,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 6
                        },
                        new
                        {
                            Id = 36,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 6
                        },
                        new
                        {
                            Id = 37,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 7
                        },
                        new
                        {
                            Id = 38,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 7
                        },
                        new
                        {
                            Id = 39,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 7
                        },
                        new
                        {
                            Id = 40,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 7
                        },
                        new
                        {
                            Id = 41,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 7
                        },
                        new
                        {
                            Id = 42,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 7
                        },
                        new
                        {
                            Id = 43,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 8
                        },
                        new
                        {
                            Id = 44,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 8
                        },
                        new
                        {
                            Id = 45,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 8
                        },
                        new
                        {
                            Id = 46,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 8
                        },
                        new
                        {
                            Id = 47,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 8
                        },
                        new
                        {
                            Id = 48,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 8
                        },
                        new
                        {
                            Id = 49,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 9
                        },
                        new
                        {
                            Id = 50,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 9
                        },
                        new
                        {
                            Id = 51,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 9
                        },
                        new
                        {
                            Id = 52,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 9
                        },
                        new
                        {
                            Id = 53,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 9
                        },
                        new
                        {
                            Id = 54,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 9
                        },
                        new
                        {
                            Id = 55,
                            Column = "A",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 10
                        },
                        new
                        {
                            Id = 56,
                            Column = "B",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 10
                        },
                        new
                        {
                            Id = 57,
                            Column = "C",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 10
                        },
                        new
                        {
                            Id = 58,
                            Column = "D",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 10
                        },
                        new
                        {
                            Id = 59,
                            Column = "E",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 10
                        },
                        new
                        {
                            Id = 60,
                            Column = "F",
                            FlightId = 1,
                            IsTaken = false,
                            Row = 10
                        });
                });

            modelBuilder.Entity("FlightCheckin.Models.Passenger", b =>
                {
                    b.HasOne("FlightCheckin.Models.Flight", null)
                        .WithMany("Passengers")
                        .HasForeignKey("FlightId");
                });

            modelBuilder.Entity("FlightCheckin.Models.Seat", b =>
                {
                    b.HasOne("FlightCheckin.Models.Passenger", "AssignedPassenger")
                        .WithMany()
                        .HasForeignKey("AssignedPassengerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlightCheckin.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedPassenger");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightCheckin.Models.Flight", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
